//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDCH
{
    public partial class AdminVerificationModal
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlModalBox;
        protected global::System.Web.UI.WebControls.Label lblModalTitle;
        protected global::System.Web.UI.WebControls.Label lblModalDetail1Title;
        protected global::System.Web.UI.WebControls.Label lblModalDetail1Value;
        protected global::System.Web.UI.WebControls.Label lblModalDetail2Title;
        protected global::System.Web.UI.WebControls.Label lblModalDetail2Value;
        protected global::System.Web.UI.WebControls.Label lblModalDetail3Title;
        protected global::System.Web.UI.WebControls.Label lblModalDetail3Value;
        protected global::System.Web.UI.WebControls.Button btnModalCancel;
        protected global::System.Web.UI.WebControls.Button btnModalApprove;
    }
}
