using System;
using System.Collections.Generic;
using System.Web;
using System.IO;

namespace DDCH
{
    public static class LanguageHelper
    {
        private static Dictionary<string, Dictionary<string, string>> translations = new Dictionary<string, Dictionary<string, string>>()
        {
            ["en"] = new Dictionary<string, string>()
            {
                ["Logo"] = "Dire Dawa Hub",
                ["Login"] = "Login",
                ["Portal"] = "Contributors Portal",
                ["HeroTitle"] = "Welcome to Dire Dawa",
                ["HeroSubtitle"] = "Your gateway to city services, community news, and real-time updates.",
                ["SearchPlaceholder"] = "Search services, news, or safety alerts...",
                ["QuickNav"] = "Quick Navigation",
                ["Water"] = "Water Status",
                ["Health"] = "Health Directory",
                ["Agri"] = "Agriculture",
                ["Jobs"] = "Job Board",
                ["Stats"] = "City Statistics",
                ["CommunityPosters"] = "Community Posters",
                ["LatestUpdate"] = "Latest Updates",
                ["FooterText"] = "The official digital gateway for the residents of Dire Dawa.",
                ["Copyright"] = "Copyright 2026 Dire Dawa City Administration.",
                ["HeroTitleMain"] = "Dire Dawa Hub",
                ["HeroSubtitleMain"] = "The Smart City Gateway for Residents & Businesses",
                ["SearchBtn"] = "Search",
                ["WaterSvc"] = "Water Services",
                ["HealthCl"] = "Health Clinics",
                ["AgriSvc"] = "Agriculture",
                ["JobP"] = "Job Portal",
                ["EduSvc"] = "Education",
                ["WaterStat"] = "Active Water Routes",
                ["HealthStat"] = "Health Clinics",
                ["MarketStat"] = "Market Reports",
                ["JobStat"] = "Job Postings",
                ["PostersHdr"] = "Community Posters",
                ["WeatherHdr"] = "Dire Dawa, Ethiopia",
                ["EduHdr"] = "Education Updates",
                ["WaterHdr"] = "Water Supply Tracker",
                ["HealthHdr"] = "Health Clinics",
                ["JobsHdr"] = "Local Job Portal",
                ["MarketHdr"] = "Agriculture Market",
                ["SafetyHdr"] = "Public Safety Alerts",
                ["StatsHdr"] = "Community Statistics",
                ["WelcomePortal"] = "Welcome to the Portal",
                ["PortalDesc"] = "Access the Dire Dawa Community Hub management system to update resources and insights.",
                ["SignIn"] = "Sign In",
                ["SignInDesc"] = "Enter your credentials to manage the hub",
                ["Email"] = "Email Address",
                ["Password"] = "Password",
                ["Remember"] = "Remember me",
                ["SignInBtn"] = "Sign Into Dashboard",
                ["NeedShare"] = "Need to share information?",
                ["RegisterLink"] = "Register as Contributor",
                ["RegHeader"] = "Contributor Registration",
                ["RegSub"] = "Join the Dire Dawa Hub community",
                ["DocReqs"] = "Document Requirements:",
                ["Req1"] = "• Upload a clear photo of your Work ID card or Government ID",
                ["Req2"] = "• File size: Max 5MB (JPG, PNG, PDF accepted)",
                ["WorkIdNum"] = "Work ID Number",
                ["DocType"] = "Document Type",
                ["UploadId"] = "ID Document Photo",
                ["ConfPass"] = "Confirm Password",
                ["RegSubmitBtn"] = "Submit for Verification",
                ["AlreadyAcc"] = "Already have an account?",
                ["SignInLink"] = "Sign in here",
                ["AdminAnalytics"] = "System Analytics",
                ["AdminUsers"] = "Identity Registry",
                ["AdminCatalog"] = "System Catalog",
                ["AdminAudit"] = "Audit Logs",
                ["AdminDashboard"] = "My Dashboard",
                ["AdminPosters"] = "Community Posters",
                ["AdminWater"] = "Water Tracker",
                ["AdminHealth"] = "Health Directory",
                ["AdminJobs"] = "Job Board",
                ["AdminAgri"] = "Agriculture",
                ["AdminSafety"] = "Public Safety",
                ["AdminStats"] = "Statistics",
                ["AdminPublic"] = "View Public Site",
                ["AdminLogout"] = "Logout",
                ["AdminSection"] = "ADMINISTRATOR",
                ["WorkspaceSection"] = "DATA WORKSPACE",
                ["AdminHubCommand"] = "️ HUB COMMAND CENTER",
                ["AdminSystemGov"] = "Global Synchronization & System Governance",
                ["AdminPendingUsers"] = "PENDING USERS",
                ["AdminPendingPosts"] = "PENDING POSTS",
                ["AdminActivePosts"] = "ACTIVE POSTS",
                ["AdminStatusTitle"] = "ADMIN STATUS",
                ["AdminOnline"] = "ONLINE",
                ["AdminUserQueue"] = "Contributor Approval Queue",
                ["AdminPostQueue"] = "Content Moderation Queue",
                ["AdminApprove"] = "Approve",
                ["AdminReject"] = "Reject",
                ["AdminEmailHdr"] = "Email",
                ["AdminWorkIdHdr"] = "Work ID",
                ["AdminCatHdr"] = "Category",
                ["AdminTitleHdr"] = "Title",
                ["AdminIdentityManager"] = "Identity & Role Manager",
                ["AdminTotalUsers"] = "Total Users",
                ["AdminVerifyMunicipal"] = "Verify municipal work IDs and authorize contributor credentials.",
                ["ContributorWorkspace"] = "Contributor Workspace",
                ["ContributorHub"] = "Data Management and Content Creation Hub",
                ["ContributorTotalPosts"] = "TOTAL POSTS",
                ["ContributorApproved"] = "APPROVED",
                ["ContributorPending"] = "PENDING",
                ["ContributorDeactivated"] = "DEACTIVATED",
                ["ContributorQuickActions"] = "Quick Actions",
                ["ContributorRecentActivities"] = "Recent Activities",
                ["ContributorPostTitle"] = "Post Title",
                ["ContributorCategory"] = "Category",
                ["ContributorStatus"] = "Status",
                ["ContributorNoActivity"] = "No activity yet. Start by submitting a post using the sidebar links above!"
            },
            ["am"] = new Dictionary<string, string>()
            {
                ["Logo"] = "ድሬ ዳዋ ሀብ",
                ["Login"] = "ግባ",
                ["Portal"] = "የአስተዋጽኦ አድራጊዎች ፖርታል",
                ["HeroTitle"] = "ወደ ድሬ ዳዋ እንኳን ደህና መጡ",
                ["HeroSubtitle"] = "ለከተማ አገልግሎቶች፣ ለማህበረሰብ ዜናዎች እና ለቀጥታ መረጃዎች መግቢያዎ።",
                ["SearchPlaceholder"] = "አገልግሎቶችን፣ ዜናዎችን ወይም የደህንነት ማስጠንቀቂያዎችን ይፈልጉ...",
                ["QuickNav"] = "ፈጣን አሰሳ",
                ["Water"] = "የውሃ ሁኔታ",
                ["Health"] = "የጤና ማውጫ",
                ["Agri"] = "ግብርና",
                ["Jobs"] = "የስራ ቦርድ",
                ["Stats"] = "የከተማ ስታቲስቲክስ",
                ["CommunityPosters"] = "የማህበረሰብ ፖስተሮች",
                ["LatestUpdate"] = "የቅርብ ጊዜ ዝመናዎች",
                ["FooterText"] = "ለድሬዳዋ ነዋሪዎች ይፋዊ የዲጂታል መግቢያ በር።",
                ["Copyright"] = "የቅጂ መብት 2026 የድሬዳዋ ከተማ አስተዳደር።",
                ["HeroTitleMain"] = "ድሬ ዳዋ ሀብ",
                ["HeroSubtitleMain"] = "ለነዋሪዎች እና ለንግድ ድርጅቶች ስማርት የከተማ መግቢያ በር",
                ["SearchBtn"] = "ፈልግ",
                ["WaterSvc"] = "የውሃ አገልግሎቶች",
                ["HealthCl"] = "የጤና ክሊኒኮች",
                ["AgriSvc"] = "ግብርና",
                ["JobP"] = "የስራ ፖርታል",
                ["EduSvc"] = "ትምህርት",
                ["WaterStat"] = "ንቁ የውሃ መስመሮች",
                ["HealthStat"] = "የጤና ክሊኒኮች",
                ["MarketStat"] = "የገበያ ሪፖርቶች",
                ["JobStat"] = "የስራ ማስታወቂያዎች",
                ["PostersHdr"] = "የማህበረሰብ ፖስተሮች",
                ["WeatherHdr"] = "ድሬ ዳዋ፣ ኢትዮጵያ",
                ["EduHdr"] = "የትምህርት ዝመናዎች",
                ["WaterHdr"] = "የውሃ አቅርቦት ተቆጣጣሪ",
                ["HealthHdr"] = "የጤና ክሊኒኮች",
                ["JobsHdr"] = "የአካባቢ የሥራ ፖርታል",
                ["MarketHdr"] = "የግብርና ገበያ",
                ["SafetyHdr"] = "የህዝብ ደህንነት ማንቂያዎች",
                ["StatsHdr"] = "የማህበረሰብ ስታቲስቲክስ",
                ["WelcomePortal"] = "ወደ ፖርታል እንኳን ደህና መጡ",
                ["PortalDesc"] = "ሃብቶችን እና ግንዛቤዎችን ለማዘመን የድሬዳዋ ማህበረሰብ መገናኛ አስተዳደር ስርዓትን ይድረሱ።",
                ["SignIn"] = "ይግቡ",
                ["SignInDesc"] = "ማዕከሉን ለማስተዳደር ምስክርነቶችን ያስገቡ",
                ["Email"] = "የኢሜል አድራሻ",
                ["Password"] = "የይለፍ ቃል",
                ["Remember"] = "አስታውሰኝ",
                ["SignInBtn"] = "ወደ ዳሽቦርድ ይግቡ",
                ["NeedShare"] = "መረጃ ማጋራት ይፈልጋሉ?",
                ["RegisterLink"] = "እንደ አስተዋጽኦ አድራጊ ይመዝገቡ",
                ["RegHeader"] = "የአስተዋጽኦ አድራጊ ምዝገባ",
                ["RegSub"] = "የድሬዳዋ ሀብ ማህበረሰብን ይቀላቀሉ",
                ["DocReqs"] = "የሰነድ መስፈርቶች፡",
                ["Req1"] = "• የሥራ መታወቂያ ካርድዎን ወይም የመንግስት መታወቂያዎን ግልጽ ፎቶ ይስቀሉ",
                ["Req2"] = "• የፋይል መጠን፡ ቢበዛ 5 ሜባ (JPG፣ PNG፣ PDF ተቀባይነት አለው)",
                ["WorkIdNum"] = "የሥራ መታወቂያ ቁጥር",
                ["DocType"] = "የሰነድ ዓይነት",
                ["UploadId"] = "የመታወቂያ ሰነድ ፎቶ",
                ["ConfPass"] = "የይለፍ ቃል ያረጋግጡ",
                ["RegSubmitBtn"] = "ለማረጋገጫ ያቅርቡ",
                ["AlreadyAcc"] = "አስቀድመው መለያ አለዎት?",
                ["SignInLink"] = "እዚህ ይግቡ",
                ["AdminAnalytics"] = "የስርዓት ትንታኔ",
                ["AdminUsers"] = "የማንነት መዝገብ",
                ["AdminCatalog"] = "የስርዓት ካታሎግ",
                ["AdminAudit"] = "የኦዲት ምዝግብ ማስታወሻዎች",
                ["AdminDashboard"] = "የእኔ ዳሽቦርድ",
                ["AdminPosters"] = "የማህበረሰብ ፖስተሮች",
                ["AdminWater"] = "የውሃ መከታተያ",
                ["AdminHealth"] = "የጤና ማውጫ",
                ["AdminJobs"] = "የስራ ቦርድ",
                ["AdminAgri"] = "ግብርና",
                ["AdminSafety"] = "የህዝብ ደህንነት",
                ["AdminStats"] = "ስታቲስቲክስ",
                ["AdminPublic"] = "ይፋዊ ጣቢያን ይመልከቱ",
                ["AdminLogout"] = "ውጣ",
                ["AdminSection"] = "አስተዳዳሪ",
                ["WorkspaceSection"] = "የስራ ቦታ",
                ["AdminHubCommand"] = "የማዕከል ትዕዛዝ ማዕከል",
                ["AdminSystemGov"] = "ዓለም አቀፍ ማመሳሰል እና የስርዓት አስተዳደር",
                ["AdminPendingUsers"] = "በመጠባበቅ ላይ ያሉ ተጠቃሚዎች",
                ["AdminPendingPosts"] = "በመጠባበቅ ላይ ያሉ ልጥፎች",
                ["AdminActivePosts"] = "ንቁ ልጥፎች",
                ["AdminStatusTitle"] = "የአስተዳዳሪ ሁኔታ",
                ["AdminOnline"] = "ኦንላይን",
                ["AdminUserQueue"] = "የአስተዋጽኦ አድራጊ ማረጋገጫ ወረፋ",
                ["AdminPostQueue"] = "የይዘት ልከኝነት ወረፋ",
                ["AdminApprove"] = "አጽድቅ",
                ["AdminReject"] = "ውድቅ አድርግ",
                ["AdminEmailHdr"] = "ኢሜል",
                ["AdminWorkIdHdr"] = "የሥራ መታወቂያ",
                ["AdminCatHdr"] = "ምድብ",
                ["AdminTitleHdr"] = "ርዕስ",
                ["AdminIdentityManager"] = "የማንነት እና የተግባር አስተዳዳሪ",
                ["AdminTotalUsers"] = "ጠቅላላ ተጠቃሚዎች",
                ["AdminVerifyMunicipal"] = "የማዘጋጃ ቤት የሥራ መታወቂያዎችን ያረጋግጡ እና የአስተዋጽኦ አድራጊ ምስክርነቶችን ይፍቀዱ።",
                ["ContributorWorkspace"] = "የአስተዋጽኦ አድራጊ የሥራ ቦታ",
                ["ContributorHub"] = "የመረጃ አያያዝ እና የይዘት ፈጠራ ማዕከል",
                ["ContributorTotalPosts"] = "ጠቅላላ ልጥፎች",
                ["ContributorApproved"] = "የጸደቁ",
                ["ContributorPending"] = "በመጠባበቅ ላይ ያሉ",
                ["ContributorDeactivated"] = "የተሰረዙ",
                ["ContributorQuickActions"] = "ፈጣን እርምጃዎች",
                ["ContributorRecentActivities"] = "የቅርብ ጊዜ እንቅስቃሴዎች",
                ["ContributorPostTitle"] = "የልጥፍ ርዕስ",
                ["ContributorCategory"] = "ምድብ",
                ["ContributorStatus"] = "ሁኔታ",
                ["ContributorNoActivity"] = "ገና ምንም እንቅስቃሴ የለም። ከላይ ያሉትን የጎን አሞሌ አገናኞችን በመጠቀም ልጥፍ በማስገባት ይጀምሩ!"
            },
            ["om"] = new Dictionary<string, string>()
            {
                ["Logo"] = "Dire Dawa Hub",
                ["Login"] = "Seeni",
                ["Portal"] = "Portal Gumaachitootaa",
                ["HeroTitle"] = "Baga Gara Diree Dawaa Dhuftan",
                ["HeroSubtitle"] = "Kalaqa keessan tajaajila magaalaa, oduu hawaasaa fi odeeffannoo yeroo dhugaaf.",
                ["SearchPlaceholder"] = "Tajaajila, oduu ykn akeekkachiisa nageenyaa barbaadi...",
                ["QuickNav"] = "Qubannoo Ariifachiisaa",
                ["Water"] = "Haala Bishaania",
                ["Health"] = "Qajeelcha Fayyaa",
                ["Agri"] = "Qonna",
                ["Jobs"] = "Boordii Hojii",
                ["Stats"] = "Istaatistiiksii Magaalaa",
                ["CommunityPosters"] = "Poostari Hawwaasaa",
                ["LatestUpdate"] = "Oduu Haaraa",
                ["FooterText"] = "Karra dijiitaalaa rasmicha jiraattota Diree Dawaatiif.",
                ["Copyright"] = "Mirgi Qubannoo 2026 Bulchiinsa Magaalaa Diree Dawaa.",
                ["HeroTitleMain"] = "Dire Dawa Hub",
                ["HeroSubtitleMain"] = "Karra Magaalaa Smart Jiraattotaaf fi Daldaltootaaf",
                ["SearchBtn"] = "Barbaadi",
                ["WaterSvc"] = "Tajaajila Bishaania",
                ["HealthCl"] = "Kiliniikota Fayyaa",
                ["AgriSvc"] = "Qonna",
                ["JobP"] = "Portal Hojii",
                ["EduSvc"] = "Barumsa",
                ["WaterStat"] = "Dhaabbilee Bishaania",
                ["HealthStat"] = "Kiliniikota Fayyaa",
                ["MarketStat"] = "Gabaasa Gabaa",
                ["JobStat"] = "Beeksisa Hojii",
                ["PostersHdr"] = "Poostari Hawwaasaa",
                ["WeatherHdr"] = "Diree Dawaa, Itoophiyaa",
                ["EduHdr"] = "Oduu Barumsaa",
                ["WaterHdr"] = "Hordoffii Bishaania",
                ["HealthHdr"] = "Kiliniikota Fayyaa",
                ["JobsHdr"] = "Portal Hojii Naannoo",
                ["MarketHdr"] = "Gabaa Qonnaa",
                ["SafetyHdr"] = "Akeekkachiisa Nageenyaa",
                ["StatsHdr"] = "Istaatistiiksii Hawaasaa",
                ["WelcomePortal"] = "Baga gara Portal dhuftan",
                ["PortalDesc"] = "Meeshaalee fi ilaalcha haaraa gochuuf sirna bulchiinsa Hub Hawaasa Diree Dawaa seenaa.",
                ["SignIn"] = "Seeni",
                ["SignInDesc"] = "Hub bulchuuf ragaa keessan galchaa",
                ["Email"] = "Imeelii",
                ["Password"] = "Jecha Icchitii",
                ["Remember"] = "Na yaadadhu",
                ["SignInBtn"] = "Gara Daashboordiitti Seeni",
                ["NeedShare"] = "Odeeffannoo qooduun barbaachisadha?",
                ["RegisterLink"] = "Akka Gumaachituutti Galmaa'i",
                ["RegHeader"] = "Galmee Gumaachituu",
                ["RegSub"] = "Hawaasa Hub Diree Dawaa tti makamaa",
                ["DocReqs"] = "Ulaagaalee Sanadaa:",
                ["Req1"] = "• Footoo qulqulluu kaardii eenyummaa hojii ykn eenyummaa mootummaa keessanii olkaa'aa",
                ["Req2"] = "• Hammamtaa faayilaa: Max 5MB (JPG, PNG, PDF ni fudhatama)",
                ["WorkIdNum"] = "Lakkoofsa Eenyummaa Hojii",
                ["DocType"] = "Gosa Sanadaa",
                ["UploadId"] = "Footoo Sanada Eenyummaa",
                ["ConfPass"] = "Jecha Icchitii Mirkaneessi",
                ["RegSubmitBtn"] = "Mirkaneessaaf Galchi",
                ["AlreadyAcc"] = "Duraan akkawuntii qabduu?",
                ["SignInLink"] = "Asitti seeni",
                ["AdminAnalytics"] = "Xiነ-ተንታኔ Sirnaa",
                ["AdminUsers"] = "Galmee Eenyummaa",
                ["AdminCatalog"] = "Kaataaloogii Sirnaa",
                ["AdminAudit"] = "Galmee Ooditii",
                ["AdminDashboard"] = "Daashboordii Koo",
                ["AdminPosters"] = "Poostari Hawwaasaa",
                ["AdminWater"] = "Hordoffii Bishaania",
                ["AdminHealth"] = "Qajeelcha Fayyaa",
                ["AdminJobs"] = "Boordii Hojii",
                ["AdminAgri"] = "Qonna",
                ["AdminSafety"] = "Nageenya Ummataa",
                ["AdminStats"] = "Istaatistiiksii",
                ["AdminPublic"] = "Marsariitii Ummataa Ilaali",
                ["AdminLogout"] = "Ba'i",
                ["AdminSection"] = "BULCHITUU",
                ["WorkspaceSection"] = "BAKKAA HOJII",
                ["AdminHubCommand"] = "GIDDU-GALA AJJAJAA HUB",
                ["AdminSystemGov"] = "Sinxiroonayizeeshinii Addunyaa fi Bulchiinsa Sirnaa",
                ["AdminPendingUsers"] = "FAYYADAMTTOOTA EEGGANNAA",
                ["AdminPendingPosts"] = "POSTIIWWAN EEGGANNAA",
                ["AdminActivePosts"] = "POSTIIWWAN NIKUU",
                ["AdminStatusTitle"] = "HAALA BULCHITUU",
                ["AdminOnline"] = "INTERNEETII IRRA",
                ["AdminUserQueue"] = "Taruu Mirkaneessa Gumaachituu",
                ["AdminPostQueue"] = "Taruu To'annoo Qabiyyee",
                ["AdminApprove"] = "Mirkaneessi",
                ["AdminReject"] = "Kufisiisi",
                ["AdminEmailHdr"] = "Imeelii",
                ["AdminWorkIdHdr"] = "Eenyummaa Hojii",
                ["AdminCatHdr"] = "Ramaddii",
                ["AdminTitleHdr"] = "Mata-duree",
                ["AdminIdentityManager"] = "Bulchiinsa Eenyummaa fi Gahee",
                ["AdminTotalUsers"] = "Fayyadamttoota Waliigalaa",
                ["AdminVerifyMunicipal"] = "Eenyummaa hojii bulchiinsa magaalaa mirkaneessuu fi ragaa gumaachituu hayyamuu.",
                ["ContributorWorkspace"] = "Bakka Hojii Gumaachituu",
                ["ContributorHub"] = "Giddu-gala Bulchiinsa Data fi Hojii Kalaqaa",
                ["ContributorTotalPosts"] = "POSTIIWWAN WALIIGALAA",
                ["ContributorApproved"] = "MIRKANEESSAME",
                ["ContributorPending"] = "EEGGANNAA IRRA",
                ["ContributorDeactivated"] = "HAGAGAME",
                ["ContributorQuickActions"] = "Gocha Ariifachiisaa",
                ["ContributorRecentActivities"] = "Gochaalee Dhihoo",
                ["ContributorPostTitle"] = "Mata-duree Postii",
                ["ContributorCategory"] = "Ramaddii",
                ["ContributorStatus"] = "Haala",
                ["ContributorNoActivity"] = "Hamma yoonaatti gochi hin jiru. Hidhamtoota barreeffama cinaa olitti fayyadamuun postii galchuun jalqabaa!"
            },
            ["so"] = new Dictionary<string, string>()
            {
                ["Logo"] = "Dire Dawa Hub",
                ["Login"] = "Gali",
                ["Portal"] = "Bogga Wax-ku-biiriyayaasha",
                ["HeroTitle"] = "Ku soo dhawaada Dire Dawa",
                ["HeroSubtitle"] = "Albaabkaaga tixraaca adeegyada magaalada, wararka bulshada iyo macluumaadka rasmiga ah.",
                ["SearchPlaceholder"] = "Raadi adeegyada, wararka ama digniinaha nabadgelyada...",
                ["QuickNav"] = "Hage Degdeg ah",
                ["Water"] = "Xaaladda Biyaha",
                ["Health"] = "Hage Caafimaad",
                ["Agri"] = "Beeraha",
                ["Jobs"] = "Guddiga Shaqada",
                ["Stats"] = "Xogta Magaalada",
                ["CommunityPosters"] = "Ogeysiisyada Bulshada",
                ["LatestUpdate"] = "Wararkii ugu dambeeyay",
                ["FooterText"] = "Albaabka rasmiga ah ee dhijitaalka ah ee dadka deegaanka Dire Dawa.",
                ["Copyright"] = "Xuquuqda daabacaadda 2026 Maamulka Magaalada Dire Dawa.",
                ["HeroTitleMain"] = "Dire Dawa Hub",
                ["HeroSubtitleMain"] = "Albaabka Magaalada Smart ee Dadka iyo Ganacsiga",
                ["SearchBtn"] = "Raadi",
                ["WaterSvc"] = "Adeegyada Biyaha",
                ["HealthCl"] = "Rugaha Caafimaadka",
                ["AgriSvc"] = "Beeraha",
                ["JobP"] = "Bogga Shaqada",
                ["EduSvc"] = "Waxbarashada",
                ["WaterStat"] = "Waddooyinka Biyaha",
                ["HealthStat"] = "Rugaha Caafimaadka",
                ["MarketStat"] = "Warbixinnada Suuqa",
                ["JobStat"] = "Shaqooyinka Bannaan",
                ["PostersHdr"] = "Ogeysiisyada Bulshada",
                ["WeatherHdr"] = "Dire Dawa, Itoobiya",
                ["EduHdr"] = "Wararka Waxbarashada",
                ["WaterHdr"] = "Raad-raaca Biyaha",
                ["HealthHdr"] = "Rugaha Caafimaadka",
                ["JobsHdr"] = "Bogga Shaqada Deegaanka",
                ["MarketHdr"] = "Suuqa Beeraha",
                ["SafetyHdr"] = "Digniinaha Amniga",
                ["StatsHdr"] = "Xogta Bulshada",
                ["WelcomePortal"] = "Ku soo dhawaada Bogga",
                ["PortalDesc"] = "Gali nidaamka maaraynta Hubka Bulshada ee Dire Dawa si aad u cusboonaysiiso agabka iyo xogta.",
                ["SignIn"] = "Gal",
                ["SignInDesc"] = "Gali aqoonsigaaga si aad u maamusho hubka",
                ["Email"] = "Cinwaanka Imeelka",
                ["Password"] = "Erayga sirta ah",
                ["Remember"] = "Isii xasuuso",
                ["SignInBtn"] = "Gali Dashboard-ka",
                ["NeedShare"] = "Ma u baahan tahay inaad macluumaad wadaagto?",
                ["RegisterLink"] = "Isu diiwaangeli sidii Wax-ku-biiriye",
                ["RegHeader"] = "Diiwaangelinta Wax-ku-biiriyaha",
                ["RegSub"] = "Ku biir bulshada Dire Dawa Hub",
                ["DocReqs"] = "Shuruudaha Dukumentiga:",
                ["Req1"] = "• Soo rar sawir cad oo kaarka aqoonsiga shaqadaada ama aqoonsiga dawladda",
                ["Req2"] = "• Cabbirka faylka: ugu badnaan 5MB (JPG, PNG, PDF waa la aqbalayaa)",
                ["WorkIdNum"] = "Lambarka aqoonsiga shaqada",
                ["DocType"] = "Nooca Dukumentiga",
                ["UploadId"] = "Sawirka Dukumentiga Aqoonsiga",
                ["ConfPass"] = "Xaqiiji Erayga sirta ah",
                ["RegSubmitBtn"] = "U soo gudbi Xaqiijinta",
                ["AlreadyAcc"] = "Horey ma u lahayd akoon?",
                ["SignInLink"] = "Halkan ka gal",
                ["AdminAnalytics"] = "Falanqaynta Nidaamka",
                ["AdminUsers"] = "Diiwaanka Aqoonsiga",
                ["AdminCatalog"] = "Buug-yaraha Nidaamka",
                ["AdminAudit"] = "Diiwaanka Hantidhawrka",
                ["AdminDashboard"] = "Dashboard-kayga",
                ["AdminPosters"] = "Ogeysiisyada Bulshada",
                ["AdminWater"] = "Raad-raaca Biyaha",
                ["AdminHealth"] = "Hage Caafimaad",
                ["AdminJobs"] = "Guddiga Shaqada",
                ["AdminAgri"] = "Beeraha",
                ["AdminSafety"] = "Badbaadada Dadweynaha",
                ["AdminStats"] = "Xogta",
                ["AdminPublic"] = "Eeg Bogga Dadweynaha",
                ["AdminLogout"] = "Ka bax",
                ["AdminSection"] = "MAAMULKA",
                ["WorkspaceSection"] = "GOOBTA SHAQADA",
                ["AdminHubCommand"] = "XARUNTA AMARKA HUB",
                ["AdminSystemGov"] = "Iskuxirka Caalamiga ah iyo Maamulka Nidaamka",
                ["AdminPendingUsers"] = "DIIWAANGELINTA SUGAYSA",
                ["AdminPendingPosts"] = "POSTIYADA SUGAYSA",
                ["AdminActivePosts"] = "POSTIYADA SHAQAYNAYA",
                ["AdminStatusTitle"] = "XALADDA MAAMULKA",
                ["AdminOnline"] = "KHADKA",
                ["AdminUserQueue"] = "Saf sugitaanka ansixinta",
                ["AdminPostQueue"] = "Safka dhex-dhexaadinta nuxurka",
                ["AdminApprove"] = "Ansixi",
                ["AdminReject"] = "Diid",
                ["AdminEmailHdr"] = "Imeelka",
                ["AdminWorkIdHdr"] = "Aqoonsiga Shaqada",
                ["AdminCatHdr"] = "Qaybta",
                ["AdminTitleHdr"] = "Cinwaanka",
                ["AdminIdentityManager"] = "Maamulaha Aqoonsiga & Kaalinta",
                ["AdminTotalUsers"] = "Warta Isticmaalayaasha",
                ["AdminVerifyMunicipal"] = "Xaqiiji aqoonsiga shaqada dawlada hoose oo oggolow aqoonsiga wax ku darsaday.",
                ["ContributorWorkspace"] = "Goobta Shaqada ee Wax-ku-biiriyaha",
                ["ContributorHub"] = "Xarunta Maamulka Xogta iyo Abuurista Nuxurka",
                ["ContributorTotalPosts"] = "POSTIYADA GUUD",
                ["ContributorApproved"] = "LA ANSIXIYAY",
                ["ContributorPending"] = "SUGAYSA",
                ["ContributorDeactivated"] = "LA JOOJIYAY",
                ["ContributorQuickActions"] = "Tallaabooyinka Degdegga ah",
                ["ContributorRecentActivities"] = "Dhaqdhaqaaqyadii Ugu Dambeeyay",
                ["ContributorPostTitle"] = "Cinwaanka Boostada",
                ["ContributorCategory"] = "Qaybta",
                ["ContributorStatus"] = "Xaaladda",
                ["ContributorNoActivity"] = "Weli wax dhaqdhaqaaq ah ma jiro. Ku billow inaad soo gudbiso boostada adoo isticmaalaya xiriiriyeyaasha dhinaca ee sare!"
            }
        };

        public static string Get(string key)
        {
            try
            {
                string lang = GetCurrentLanguage();
                if (translations.ContainsKey(lang) && translations[lang].ContainsKey(key))
                {
                    return translations[lang][key];
                }
                // Fallback to English
                if (translations.ContainsKey("en") && translations["en"].ContainsKey(key))
                {
                    return translations["en"][key];
                }
            }
            catch (Exception ex)
            {
                LogError("Get: " + key, ex);
            }
            return key; // Return the key as fallback
        }

        public static string GetCurrentLanguage()
        {
            try
            {
                if (HttpContext.Current != null && HttpContext.Current.Session != null && HttpContext.Current.Session["Lang"] != null)
                {
                    return HttpContext.Current.Session["Lang"].ToString();
                }
            }
            catch { }
            return "en"; // Default
        }

        public static void SetLanguage(string lang)
        {
            try
            {
                if (HttpContext.Current != null && HttpContext.Current.Session != null)
                {
                    HttpContext.Current.Session["Lang"] = lang;
                }
            }
            catch (Exception ex)
            {
                LogError("SetLanguage: " + lang, ex);
            }
        }

        private static void LogError(string context, Exception ex)
        {
            try
            {
                string logPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App_Data", "errors.log");
                string message = string.Format("[{0}] LanguageHelper Context: {1} - Error: {2}\n",
                    DateTime.Now.ToString(), context, ex.Message);
                File.AppendAllText(logPath, message);
            }
            catch { }
        }
    }
}
